<?php require_once __DIR__ . "/../layouts/header.php"; ?>

<?php
$question_image_url =
    "assets/img/" . $exam_set_alias . "_Q" . $question_number . ".png";
$choices_count = $question["choices_count"];
$correct_choice_index = $question["correct_choice_index"];
$choice_labels = range("A", "Z");
?>

<div class="row">
    <div class="col-12 col-lg-8 col-xl-9">
        <img class="img-fluid mb-5" src="<?= htmlspecialchars(
            $question_image_url
        ) ?>">
    </div>
    <div class="col-12 col-lg-4 col-xl-3 order-lg-first">
        <div class="row gy-4 row-cols-lg-1 mb-5">
            <?php for ($i = 0; $i < $choices_count; $i++): ?>
                <div class="col-6 order-lg-5">
                    <div class="card">
                        <div class="card-body p-4">
                            <a class="stretched-link text-decoration-none" href="#">
                                <h4 class="fw-bold text-center"><?= $choice_labels[
                                    $i
                                ] ?>.</h4>
                            </a>
                        </div>
                    </div>
                </div>
            <?php endfor; ?>
            <div class="col-12 order-lg-4">
                <hr>
            </div>
            <div class="col-12 text-center order-lg-3" id="submit-col">
                <button class="btn btn-primary btn-lg h-100 w-100" id="submit-btn" type="button">Submit</button>
            </div>
            <div class="col-12 text-center d-none order-lg-3" id="explanation-col">
                <div class="modal fade" role="dialog" tabindex="-1" id="explanation-1">
                    <div class="modal-dialog modal-fullscreen" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title fw-bold">Explanation</h4>
                                <button class="btn-close" type="button" aria-label="Close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <p class="lead text-start">This is an explanation</p>
                            </div>
                            <div class="modal-footer">
                                <span class="me-auto">Generated by&nbsp; <span class="badge rounded-pill bg-secondary">gpt-4o-mini</span>
                                </span>
                                <button class="btn btn-light btn-sm" type="button">Regenerate explanation</button>
                                <button class="btn btn-primary btn-lg d-none d-sm-inline-block" type="button" data-bs-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal fade" role="dialog" tabindex="-1" id="explanation-2">
                    <div class="modal-dialog modal-fullscreen" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title fw-bold">Explanation</h4>
                                <button class="btn-close" type="button" aria-label="Close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <p class="lead text-start">This is an explanation</p>
                            </div>
                            <div class="modal-footer">
                                <span class="me-auto">Generated by&nbsp; <span class="badge rounded-pill bg-secondary">gpt-4o-mini</span>
                                </span>
                                <button class="btn btn-light btn-sm" type="button">Regenerate explanation</button>
                                <button class="btn btn-primary btn-lg d-none d-sm-inline-block" type="button" data-bs-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-outline-primary btn-lg active h-100 w-100" type="button" data-bs-target="#explanation-1" data-bs-toggle="modal">See explanation</button>
            </div>
            <div class="col text-center order-lg-2">
                <a class="btn btn-outline-primary btn-lg h-100 w-100" role="button" href="#">Random Question</a>
            </div>
            <div class="col text-center order-lg-1">
                <a class="btn btn-outline-primary btn-lg h-100 w-100" role="button" href="#">Next Question</a>
            </div>
        </div>
    </div>
</div>
<script>
    var quizConfig = {
        correctAnswer: <?= $question["correct_choice_index"] ?>
    };
</script>

<?php require_once __DIR__ . "/../layouts/footer.php"; ?>
